# Generated by Django 5.2.1 on 2025-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_remove_conversation_is_read_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediauser',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
