# Generated by Django 5.2.1 on 2025-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_socialmediauser_profile_pic_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_from_user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business'), ('ai', 'AI')], default='business', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
